image: ubuntu:latest

stages:
  - build

build_apk_arm64-v8a:
  stage: build
  before_script:
    - apt update -y
    - apt upgrade -y
    - echo 2 > input.txt
    - echo 85 >> input.txt
    - apt install -y python3-pip python3-dev build-essential
    - apt install -y  git unzip zip ant automake gcc patch libssl-dev libtool
    - apt install -y default-jdk < input.txt
    - pip3 install buildozer cython virtualenv cmake
  script:
    - buildozer -v android debug
  artifacts:
    paths:
      - bin/*.apk
  when: manual
