image: ubuntu:latest

stages:
  - setup
  - build

setup_enviorment:
  stage: setup
  script:
    - apt update -y
    - apt upgrade -y
    - apt install -y python3-pip python3-dev build-essential
    - apt install -y --no-install-recommends default-jdk

build_apk_arm64-v8a:
  stage: build
  script:
    buildozer -v android debug
  artifacts:
    paths:
      - bin/*.apk
